name: GitHub Actions PyTest Demo and sequence and deployment to Heroku - Vamonos Finance
on: 
  push:
    branches-ignore: [main, QA, dev, stage]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest ./tests/smoke/smoke-test.py
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@v1
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ambiente-dev-pr" 
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
    
